import React from "react";

function PrivacyPolicy() {
  return (
    <div style={{ margin: 20 }}>
      {/* <div style={{fontWeight: 'bold', fontSize: 25, marginBottom: 20}}>Privacy Policy</div>
      <div style={{marginBottom: 15}}>Last updated: June 20, 2021</div>
      <div style={{marginBottom: 15}}>
        This Privacy Policy describes Our policies and procedures on the
        collection, use and disclosure of Your information when You use the
        Service and tells You about Your privacy rights and how the law protects
        You.
      </div>
      <div style={{marginBottom: 20}}>
        We use Your Personal data to provide and improve the Service. By using
        the Service, You agree to the collection and use of information in
        accordance with this Privacy Policy. This Privacy Policy has been
        created with the help of the Privacy Policy Generator.
      </div>
      <div style={{fontWeight: 'bold', fontSize: 22, marginBottom: 20}}>Interpretation and Definitions</div>
      <div style={{fontWeight: 'bold', fontSize: 20, marginBottom: 20}}>Interpretation</div>
      <div>
        The words of which the initial letter is capitalized have meanings
        defined under the following conditions. The following definitions shall
        have the same meaning regardless of whether they appear in singular or
        in plural.
      </div>
      <div style={{fontWeight: 'bold', fontSize: 20, marginBottom: 20, marginTop: 20}}>Definitions</div>
      <div>For the purposes of this Privacy Policy:</div>
      <ul>

      <li style={{marginTop: 15}}>
        Account means a unique account created for You to access our Service or
        parts of our Service.
      </li>
      <li style={{marginTop: 15}}>
        Company (referred to as either "the Company", "We", "Us" or "Our" in
        this Agreement) refers to Voyage Nepal.
      </li>
      <li style={{marginTop: 15}}>
        Cookies are small files that are placed on Your computer, mobile device
        or any other device by a website, containing the details of Your
        br/owsing history on that website among its many uses.
      </li>
      <li style={{marginTop: 15}}>Country refers to: Nepal</li>
      <li style={{marginTop: 15}}>
        Device means any device that can access the Service such as a computer,
        a cellphone or a digital tablet.
      </li>
      <li style={{marginTop: 15}}>
        Personal Data is any information that relates to an identified or
        identifiable individual.
      </li>
      <li style={{marginTop: 15}}>Service refers to the Website.</li>
      <li style={{marginTop: 15}}>
        Service Provider means any natural or legal person who processes the
        data on behalf of the Company. It refers to third-party companies or
        individuals employed by the Company to facilitate the Service, to
        provide the Service on behalf of the Company, to perform services
        related to the Service or to assist the Company in analyzing how the
        Service is used.
      </li>
      <li style={{marginTop: 15}}>
        Usage Data refers to data collected automatically, either generated by
        the use of the Service or from the Service infrastructure itself (for
        example, the duration of a page visit).
      </li>
      <li style={{marginTop: 15}}>
        Website refers to Voyage Nepal, accessible from
        https://www.voyagenepal.com/
      </li>
      <li style={{marginTop: 15}}>
        You means the individual accessing or using the Service, or the company,
        or other legal entity on behalf of which such individual is accessing or
        using the Service, as applicable.
      </li>
      </ul>
      <div style={{fontWeight: 'bold', fontSize: 25, marginBottom: 20}}>Collecting and Using Your Personal Data</div>
      <div style={{fontWeight: 'bold', fontSize: 20, marginBottom: 20}}>Types of Data Collected</div>
      <div style={{fontWeight: 'bold', marginBottom: 20}}>Personal Data</div>
      <div>
        While using Our Service, We may ask You to provide Us with certain
        personally identifiable information that can be used to contact or
        identify You. Personally identifiable information may include, but is
        not limited to:
      </div>
      <ul>
      <li style={{marginTop: 15}}>Email address</li>
      <li style={{marginTop: 15}}>First name and last name</li>
      <li style={{marginTop: 15}}>Phone number</li>
      <li style={{marginTop: 15}}>Address, State, Province, ZIP/Postal code, City</li>
      <li style={{marginTop: 15}}>Usage Data</li>
      </ul>
      <div style={{fontWeight: 'bold', marginBottom: 20}}>Usage Data</div>
      <div style={{marginBottom: 13}}>Usage Data is collected automatically when using the Service.</div>
      <div style={{marginBottom: 13}}>
        Usage Data may include information such as Your Device's Internet
        Protocol address (e.g. IP address), br/owser type, br/owser version, the
        pages of our Service that You visit, the time and date of Your visit,
        the time spent on those pages, unique device identifiers and other
        diagnostic data.
      </div>
      <div style={{marginBottom: 13}}>
        When You access the Service by or through a mobile device, We may
        collect certain information automatically, including, but not limited
        to, the type of mobile device You use, Your mobile device unique ID, the
        IP address of Your mobile device, Your mobile operating system, the type
        of mobile Internet br/owser You use, unique device identifiers and other
        diagnostic data.
      </div>
      <div style={{marginBottom: 13}}>
        We may also collect information that Your br/owser sends whenever You
        visit our Service or when You access the Service by or through a mobile
        device.
      </div>
      <div style={{fontWeight: 'bold', marginBottom: 20}}>Tracking Technologies and Cookies</div>
      <div style={{marginBottom: 13}}>
        We use Cookies and similar tracking technologies to track the activity
        on Our Service and store certain information. Tracking technologies used
        are beacons, tags, and scripts to collect and track information and to
        improve and analyze Our Service. The technologies We use may include:
      </div>
      <ul>
      <li style={{marginBottom: 13}}>
        <b>Cookies or Br/owser Cookies.</b> A cookie is a small file placed on Your
        Device. You can instruct Your br/owser to refuse all Cookies or to
        indicate when a Cookie is being sent. However, if You do not accept
        Cookies, You may not be able to use some parts of our Service. Unless
        you have adjusted Your br/owser setting so that it will refuse Cookies,
        our Service may use Cookies.
      </li>
      <li style={{marginBottom: 13}}>
        <b>Flash Cookies.</b> Certain features of our Service may use local stored
        objects (or Flash Cookies) to collect and store information about Your
        preferences or Your activity on our Service. Flash Cookies are not
        managed by the same br/owser settings as those used for Br/owser Cookies.
        For more information on how You can delete Flash Cookies, please read
        "Where can I change the settings for disabling, or deleting local shared
        objects?" available at
        https://helpx.adobe.com/flash-player/kb/disable-local-shared-objects-flash.html#main_Where_can_I_change_the_settings_for_disabling__or_deleting_local_shared_objects_
      </li>
      <li>
        <b>Web Beacons.</b> Certain sections of our Service and our emails may contain
        small electronic files known as web beacons (also referred to as clear
        gifs, pixel tags, and single-pixel gifs) that permit the Company, for
        example, to count users who have visited those pages or opened an email
        and for other related website statistics (for example, recording the
        popularity of a certain section and verifying system and server
        integrity).
      </li>
      </ul>
      <div style={{marginBottom: 13}}>
        Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies
        remain on Your personal computer or mobile device when You go offline,
        while Session Cookies are deleted as soon as You close Your web br/owser.
        You can learn more about cookies here: All About Cookies by TermsFeed.
      </div>
      <div style={{marginBottom: 13}}>
        We use both Session and Persistent Cookies for the purposes set out
        below:
      </div> */}
      <p>
        <strong>Privacy Policy for Voyage Nepal</strong>
      </p>
      <p>
        Voyage Nepal one of our main priorities is the privacy of our visitors.
        This Privacy Policy document contains types of information that is
        collected and recorded by Voyage Nepal and how we use it.
      </p>
      <p>
        If you have additional questions or require more information about our
        Privacy Policy, do not hesitate to contact us.
      </p>
      <p>
        This privacy policy applies only to our online activities and is valid
        for visitors to our website with regards to the information that they
        shared and/or collect in&Voyage Nepal. This policy is not applicable to
        any information collected offline or via channels other than this
        website.
      </p>
      <p><b>Consent</b></p>
      {/* <p>
        <br />
      </p> */}
      <p>
        By using our website, you hereby consent to our Privacy Policy and agree
        to its terms. This Privacy Policy has been generated with the{" "}
        <a href="https://www.privacypolicygenerator.info/">
          <span class="s1">Privacy Policy Generator</span>
        </a>{" "}
        which is available from{" "}
        <a href="https://www.privacypolicygenerator.info/">
          <span class="s1">https://www.privacypolicygenerator.info/</span>
        </a>
        <span class="Apple-converted-space">&</span>
      </p>
      {/* <p>
        <br />
      </p> */}
      <p>
        <strong>Information we collect</strong>
      </p>
      {/* <p>
        <br />
      </p> */}
      <p>
        The personal information that you are asked to provide, and the reasons
        why you are asked to provide it, will be made clear to you at the point
        we ask you to provide your personal information.
      </p>
      {/* <p>
        <br />
      </p> */}
      <p>
        If you contact us directly, we may receive additional information about
        you such as your name, email address, phone number, the contents of the
        message and/or attachments you may send us, and any other information
        you may choose to provide.
      </p>
      {/* <p>
        <br />
      </p> */}
      <p>
        When you register for an Account, we may ask for your contact
        information, including items such as name, company name, address, email
        address, and telephone number.
      </p>
      {/* <p>
        <br />
      </p> */}
      <p>
        <strong>How we use your information</strong>
      </p>
      {/* <p>
        <br />
      </p> */}
      <p>We use the information we collect in various ways, including to:</p>
      {/* <p>
        <br />
      </p> */}
      <ul>
        <li>Provide, operate, and maintain our website</li>
        <li>Improve, personalize, and expand our website</li>
        <li>Understand and analyze how you use our website</li>
        <li>Develop new products, services, features, and functionality</li>
        <li>
          Communicate with you, either directly or through one of our partners,
          including for customer service, to provide you with updates and other
          information relating to the website, and for marketing and promotional
          purposes
        </li>
        <li>Send you emails</li>
        <li>Find and prevent fraud</li>
        <li>Log Files</li>
      </ul>
      {/* <p>
        <br />
      </p> */}
      <p>
        Voyage Nepal follows a standard procedure of using log files. These
        files log visitors when they visit websites. All hosting companies do
        this and a part of hosting services' analytics. The information
        collected by log files include internet protocol (IP) addresses,
        br/owser type, Internet Service Provider (ISP), date and time stamp,
        referring/exit pages, and possibly the number of clicks. These are not
        linked to any information that is personally identifiable. The purpose
        of the information is for analyzing trends, administering the site,
        tracking users' movement on the website, and gathering demographic
        information.
      </p>
      {/* <p>
        <br />
      </p> */}
      <p>
        <strong>Cookies and Web Beacons</strong>
      </p>
      {/* <p>
        <br />
      </p> */}
      <p>
        Like any other website, Voyage Nepal uses "cookies". These cookies are
        used to store information including visitors' preferences, and the pages
        on the website that the visitor accessed or visited. The information is
        used to optimize the users' experience by customizing our web page
        content based on visitors' br/owser type and/or other information.
      </p>
      {/* <p>
        <br />
      </p> */}
      <p>
        <strong>Flash Cookies.</strong>
      </p>
      {/* <p>
        <br />
      </p> */}
      <p>
        Certain features of our Service may use local stored objects (or Flash
        Cookies) to collect and store information about Your preferences or Your
        activity on our Service. Flash Cookies are not managed by the same
        br/owser settings as those used for Br/owser Cookies. For more
        information on how You can delete Flash Cookies, please read "Where can
        I change the settings for disabling, or deleting local shared objects?"
        available at
        <a href="https://helpx.adobe.com/flash-player/kb/disable-local-shared-objects-flash">
          <span class="s1">
            https://helpx.adobe.com/flash-player/kb/disable-local-shared-objects-flash.
          </span>
        </a>
      </p>
      <p>
        Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies
        remain on Your personal computer or mobile device when You go offline,
        while Session Cookies are deleted as soon as You close Your web
        br/owser. You can learn more about cookies here: All About Cookies by
        TermsFeed.
      </p>
      {/* <p>
        <br />
      </p> */}

      <p>
        <strong>Advertising Partners Privacy Policies</strong>
      </p>
      {/* <p>
        <br />
      </p> */}
      <p>
        You may consult this list to find the Privacy Policy for each of the
        advertising partners of&Voyage Nepal.
      </p>
      {/* <p>
        <br />
      </p> */}
      <p>
        Third-party ad servers or ad networks uses technologies like cookies,
        JavaScript, or Web Beacons that are used in their respective
        advertisements and links that appear on&Voyage Nepal, which are sent
        directly to users' br/owser. They automatically receive your IP address
        when this occurs. These technologies are used to measure the
        effectiveness of their advertising campaigns and/or to personalize the
        advertising content that you see on websites that you visit.
      </p>
      {/* <p>
        <br />
      </p> */}
      <p>
        Note that Voyage Nepal has no access to or control over these cookies that
        are used by third-party advertisers.
      </p>
      {/* <p>
        <br />
      </p> */}
      <p>
        <strong>Third-Party Privacy Policies</strong>
      </p>
      {/* <p>
        <br />
      </p> */}
      <p>
        Voyage Nepal's Privacy Policy does not apply to other advertisers or
        websites. Thus, we are advising you to consult the respective Privacy
        Policies of these third-party ad servers for more detailed information.
        It may include their practices and instructions about how to opt-out of
        certain options. You may find a complete list of these Privacy Policies
        and their links here: Privacy Policy Links.
      </p>
      {/* <p>
        <br />
      </p> */}
      <p>
        You can choose to disable cookies through your individual br/owser
        options. To know more detailed information about cookie management with
        specific web br/owsers, it can be found at the br/owsers' respective
        websites.{" "}
        <a href="https://www.privacypolicygenerator.info/privacy-policy-cookies-clauses/">
          <span class="s1">What Are Cookies?</span>
        </a>
      </p>
      {/* <p>
        <br />
      </p> */}
      <p>
        <strong>
          CCPA Privacy Policy (Do Not Sell My Personal Information)
        </strong>
      </p>
      {/* <p>
        <br />
      </p> */}
      <p>
        Under the CCPA, among other rights, California consumers have the right
        to:
      </p>
      {/* <p>
        <br />
      </p> */}
      <ul>
        <li>
          Request that a business that collects a consumer's personal data
          disclose the categories and specific pieces of personal data that a
          business has collected about consumers.
        </li>
        <li>
          Request that a business delete any personal data about the consumer
          that a business has collected.
        </li>
        <li>
          Request that a business that sells a consumer's personal data, not
          sell the consumer's personal data.
        </li>
      </ul>
      {/* <p>
        <br />
      </p> */}
      <p>
        If you make a request, we have one month to respond to you. If you would
        like to exercise any of these rights, please contact us.
      </p>
      {/* <p>
        <br />
      </p> */}
      <p>
        <strong>GDPR Privacy Policy (Data Protection Rights)</strong>
      </p>
      {/* <p>
        <br />
      </p> */}
      <p>
        We would like to make sure you are fully aware of all of your data
        protection rights. Every user is entitled to the following:
      </p>
      {/* <p>
        <br />
      </p> */}
      <ul>
        <li>
          The right to access &ndash; You have the right to request copies of
          your personal data. We may charge you a small fee for this service.
        </li>
        <li>
          The right to rectification &ndash; You have the right to request that
          we correct any information you believe is inaccurate. You also have
          the right to request that we complete the information you believe is
          incomplete.
        </li>
        <li>
          The right to erasure &ndash; You have the right to request that we
          erase your personal data, under certain conditions.
        </li>
        <li>
          The right to restrict processing &ndash; You have the right to request
          that we restrict the processing of your personal data, under certain
          conditions.
        </li>
        <li>
          The right to object to processing &ndash; You have the right to object
          to our processing of your personal data, under certain conditions.
        </li>
        <li>
          The right to data portability &ndash; You have the right to request
          that we transfer the data that we have collected to another
          organization, or directly to you, under certain conditions.
        </li>
      </ul>
      {/* <p>
        <br />
      </p> */}
      <p>
        If you make a request, we have one month to respond to you. If you would
        like to exercise any of these rights, please contact us.
      </p>
      {/* <p>
        <br />
      </p> */}
      <p>
        <strong>Children's Information</strong>
      </p>
      {/* <p>
        <br />
      </p> */}
      <p>
        Another part of our priority is adding protection for children while
        using the internet. We encourage parents and guardians to observe,
        participate in, and/or monitor and guide their online activity.
      </p>
      {/* <p>
        <br />
      </p> */}
      <p>
        Voyage Nepal does not knowingly collect any Personal Identifiable
        Information from children under the age of 13. If you think that your
        child provided this kind of information on our website, we strongly
        encourage you to contact us immediately and we will do our best efforts
        to promptly remove such information from our records.
      </p>
      {/* <p>
        <br />
      </p> */}
      <p>
        <strong>Questions</strong>
      </p>
      {/* <p>
        <br />
      </p> */}
      <p>
        If you have any questions about this Privacy Policy, please contact us.
      </p>
      {/* <div>Necessary / Essential Cookies</div>
      <div>Type: Session Cookies</div>
      <div>Administered by: Us</div>
      <div>
        Purpose: These Cookies are essential to provide You with services
        available through the Website and to enable You to use some of its
        features. They help to authenticate users and prevent fraudulent use of
        user accounts. Without these Cookies, the services that You have asked
        for cannot be provided, and We only use these Cookies to provide You
        with those services.
      </div>
      <div>Cookies Policy / Notice Acceptance Cookies</div>
      <div>Type: Persistent Cookies</div>
      <div>Administered by: Us</div>
      <div>
        Purpose: These Cookies identify if users have accepted the use of
        cookies on the Website.
      </div>
      <div>Functionality Cookies</div>
      <div>Type: Persistent Cookies</div>
      <div>Administered by: Us</div>
      <div>
        Purpose: These Cookies allow us to remember choices You make when You
        use the Website, such as remembering your login details or language
        preference. The purpose of these Cookies is to provide You with a more
        personal experience and to avoid You having to re-enter your preferences
        every time You use the Website.
      </div>
      <div>
        For more information about the cookies we use and your choices regarding
        cookies, please visit our Cookies Policy or the Cookies section of our
        Privacy Policy.
      </div>
      <div>Use of Your Personal Data</div>
      <div>The Company may use Personal Data for the following purposes:</div>
      <div>
        To provide and maintain our Service, including to monitor the usage of
        our Service.
      </div>
      <div>
        To manage Your Account: to manage Your registration as a user of the
        Service. The Personal Data You provide can give You access to different
        functionalities of the Service that are available to You as a registered
        user.
      </div>
      <div>
        For the performance of a contract: the development, compliance and
        undertaking of the purchase contract for the products, items or services
        You have purchased or of any other contract with Us through the Service.
      </div>
      <div>
        To contact You: To contact You by email, telephone calls, SMS, or other
        equivalent forms of electronic communication, such as a mobile
        application's push notifications regarding updates or informative
        communications related to the functionalities, products or contracted
        services, including the security updates, when necessary or reasonable
        for their implementation.
      </div>
      <div>
        To provide You with news, special offers and general information about
        other goods, services and events which we offer that are similar to
        those that you have already purchased or enquired about unless You have
        opted not to receive such information.
      </div>
      <div>
        To manage Your requests: To attend and manage Your requests to Us.
      </div>
      <div>
        For business transfers: We may use Your information to evaluate or
        conduct a merger, divestiture, restructuring, reorganization,
        dissolution, or other sale or transfer of some or all of Our assets,
        whether as a going concern or as part of bankruptcy, liquidation, or
        similar proceeding, in which Personal Data held by Us about our Service
        users is among the assets transferred.
      </div>
      <div>
        For other purposes: We may use Your information for other purposes, such
        as data analysis, identifying usage trends, determining the
        effectiveness of our promotional campaigns and to evaluate and improve
        our Service, products, services, marketing and your experience.
      </div>
      <div>
        We may share Your personal information in the following situations:
      </div>
      <div>
        With Service Providers: We may share Your personal information with
        Service Providers to monitor and analyze the use of our Service, to
        contact You.
      </div>
      <div>
        For business transfers: We may share or transfer Your personal
        information in connection with, or during negotiations of, any merger,
        sale of Company assets, financing, or acquisition of all or a portion of
        Our business to another company.
      </div>
      <div>
        With Affiliates: We may share Your information with Our affiliates, in
        which case we will require those affiliates to honor this Privacy
        Policy. Affiliates include Our parent company and any other
        subsidiaries, joint venture partners or other companies that We control
        or that are under common control with Us.
      </div>
      <div>
        With business partners: We may share Your information with Our business
        partners to offer You certain products, services or promotions.
      </div>
      <div>
        With other users: when You share personal information or otherwise
        interact in the public areas with other users, such information may be
        viewed by all users and may be publicly distributed outside.
      </div>
      <div>
        With Your consent: We may disclose Your personal information for any
        other purpose with Your consent.
      </div>
      <div>Retention of Your Personal Data</div>
      <div>
        The Company will retain Your Personal Data only for as long as is
        necessary for the purposes set out in this Privacy Policy. We will
        retain and use Your Personal Data to the extent necessary to comply with
        our legal obligations (for example, if we are required to retain your
        data to comply with applicable laws), resolve disputes, and enforce our
        legal agreements and policies.
      </div>
      <div>
        The Company will also retain Usage Data for internal analysis purposes.
        Usage Data is generally retained for a shorter period of time, except
        when this data is used to strengthen the security or to improve the
        functionality of Our Service, or We are legally obligated to retain this
        data for longer time periods.
      </div>
      <div>Transfer of Your Personal Data</div>
      <div>
        Your information, including Personal Data, is processed at the Company's
        operating offices and in any other places where the parties involved in
        the processing are located. It means that this information may be
        transferred to — and maintained on — computers located outside of Your
        state, province, country or other governmental jurisdiction where the
        data protection laws may differ than those from Your jurisdiction.
      </div>
      <div>
        Your consent to this Privacy Policy followed by Your submission of such
        information represents Your agreement to that transfer.
      </div>
      <div>
        The Company will take all steps reasonably necessary to ensure that Your
        data is treated securely and in accordance with this Privacy Policy and
        no transfer of Your Personal Data will take place to an organization or
        a country unless there are adequate controls in place including the
        security of Your data and other personal information.
      </div>
      <div>Disclosure of Your Personal Data</div>
      <div>Business Transactions</div>
      <div>
        If the Company is involved in a merger, acquisition or asset sale, Your
        Personal Data may be transferred. We will provide notice before Your
        Personal Data is transferred and becomes subject to a different Privacy
        Policy.
      </div>
      <div>Law enforcement</div>
      <div>
        Under certain circumstances, the Company may be required to disclose
        Your Personal Data if required to do so by law or in response to valid
        requests by public authorities (e.g. a court or a government agency).
      </div>
      <div>Other legal requirements</div>
      <div>
        The Company may disclose Your Personal Data in the good faith belief
        that such action is necessary to:
      </div>
      <div>
      Comply with a legal obligation
Protect and defend the rights or property of the Company
Prevent or investigate possible wrongdoing in connection with the Service
Protect the personal safety of Users of the Service or the public
Protect against legal liability
Security of Your Personal Data
The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.

Children's Privacy
Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.

If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.

Links to Other Websites
Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.

We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.

Changes to this Privacy Policy
We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.

We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.

You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.

Contact Us
If you have any questions about this Privacy Policy, You can contact us:

By email: voyagenepal@outlook.com

By phone number: +9779861068895
      </div> */}
    </div>
  );
}

export default PrivacyPolicy;
