export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL'

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL'

export const RESET_PASSWORD = 'RESET PASSWORD'
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL'

export const USER_EMAIL = 'USER_EMAIL'

export const LOGIN_USER_DETAILS = 'LOGIN_USER_DETAILS'

export const FETCH_CATEGORY = 'FETCH_CATEGORY'

export const FETCH_PLACE = 'FETCH_PLACE'

export const RECOMMENDED_PLACE = 'RECOMMENDED_PLACE'

export const GET_PLACE = 'GET_PLACE'
export const GET_PLACE_SUCCESS = 'GET_PLACE_SUCCESS'
export const GET_PLACE_FAIL = 'GET_PLACE_FAIL'

export const REVIEW = 'REVIEW'
export const REVIEW_SUCCESS = 'REVIEW_SUCCESS'
export const REVIEW_FAIL = 'REVIEW_FAIL'